from typing import Required, TypedDict


class PageInfoResult(TypedDict):
    page_number: int
    has_text: bool
    has_images: bool
    likely_scanned: bool
    width: float
    height: float


class DocumentMetadataResult(TypedDict):
    title: str
    author: str
    producer: str
    creator: str


class DocumentInfoResult(TypedDict):
    page_count: int
    file_size_bytes: int
    is_encrypted: bool
    has_text_content: bool
    has_annotations: bool
    existing_annotation_count: int
    metadata: DocumentMetadataResult
    pages: list[PageInfoResult]


class TextBlockResult(TypedDict):
    text: str
    x0: float
    y0: float
    x1: float
    y1: float
    block_number: int
    line_number: int


class PageTextResult(TypedDict):
    page_number: int
    text: str
    blocks: list[TextBlockResult]


class SuggestionInputItem(TypedDict, total=False):
    """Input shape passed to get_suggestion_annotations.

    `text` is required (despite total=False; Required[] enforces this even
    with total=False). `page_number` is optional (None = search all pages,
    otherwise 0-indexed page). The metadata fields (reason, confidence,
    explanation, recommendation) are echoed verbatim onto each output
    annotation; pdf-core does not interpret them.
    """

    text: Required[str]
    page_number: int | None
    reason: str
    confidence: float
    explanation: str
    recommendation: str


class AnnotationResult(TypedDict):
    """One per-rect annotation with input metadata echoed.

    Returned in `SuggestionAnnotationsResult.annotations` (Phase 2 onward).
    `annotation_id` is deterministic from page + rect coords, generated by
    the same algorithm as `RedactionLogEntryResult.redaction_id`.
    `page` is zero-indexed. The four metadata fields (`reason`, `confidence`,
    `explanation`, `recommendation`) are echoed verbatim from the originating
    SuggestionInputItem — pdf-core does not interpret them.
    """

    annotation_id: str
    page: int
    text: str
    x0: float
    y0: float
    x1: float
    y1: float
    reason: str
    confidence: float
    explanation: str
    recommendation: str


class SuggestionAnnotationsResult(TypedDict):
    """Output of get_suggestion_annotations."""

    xfdf: str
    total_annotations: int
    annotations: list[AnnotationResult]


class RedactionStyleConfig(TypedDict, total=False):
    fill_color: str
    border_color: str
    text_color: str
    icon_png: bytes | None
    label_prefix: str


class RedactionLogEntryResult(TypedDict):
    redaction_id: str
    page: int
    x0: float
    y0: float
    x1: float
    y1: float


class RedactionResult(TypedDict):
    pdf_data: bytes
    redactions_applied: int
    content_hash: bytes
    redaction_log: list[RedactionLogEntryResult]


class RedactionVerificationEntry(TypedDict):
    redaction_id: str
    page: int
    passed: bool
    residual_text: list[str]
    has_residual_images: bool


class VerifyRedactionsResult(TypedDict):
    all_passed: bool
    entries: list[RedactionVerificationEntry]


class RiskyAnnotationFinding(TypedDict):
    annotation_id: str
    page: int
    x0: float
    y0: float
    x1: float
    y1: float
    source_subtype: str  # "Square" | "Circle" | "Polygon" | "Ink"
    has_residual_text: bool
    has_residual_images: bool


class DetectRiskyAnnotationsResult(TypedDict):
    findings: list[RiskyAnnotationFinding]
    total_findings: int
